export const LETTRES = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
export const CHIFFRES = '1234567890'.split('');

export const SYMBOLES = [
  { id: 'etoile', nom: 'Étoile', d: '*' },
  { id: 'carre_blanc', nom: 'Carré blanc', d: '□' },
  { id: 'triangle_noir', nom: 'Triangle noir', d: '▲' },
  { id: 'losange_blanc', nom: 'Losange blanc', d: '◇' },
  { id: 'eclair', nom: 'Éclair', d: '⚡︎' },
  { id: 'sigma', nom: 'Sigma', d: 'Σ' },
  { id: 'coeur_blanc', nom: 'Cœur blanc', d: '♡' },
  { id: 'db', nom: 'db', d: 'db' },
  { id: 'feminin', nom: 'Féminin (Vénus)', d: '♀' },
  { id: 'masculin', nom: 'Masculin (Mars)', d: '♂' },
  { id: 'taureau', nom: 'Taureau', d: '♉︎' },
  { id: 'pied_de_mouche', nom: 'Pied-de-mouche', d: '¶' },
  { id: 'dollar', nom: 'Dollar', d: '$' },
  { id: 'psi', nom: 'Psi', d: 'Ψ' },
  { id: 'pour_tout', nom: 'Pour tout', d: '∀' },
  { id: 'yen', nom: 'Yen', d: '¥' },
  { id: 'bl_script', nom: 'BL script', d: 'ɮ' },
  { id: 'je_cyrillique', nom: 'Jé cyrillique', d: 'Ж' },
  { id: 'tche_serbe', nom: 'Tché serbe', d: 'Ћ' },
  { id: 'shekel', nom: 'Shekel', d: '₪' },
  { id: 'presque_egal', nom: 'Presque égal', d: '≈' },
  { id: 'croisillon', nom: 'Croisillon', d: '#' },
  { id: 'paragraphe', nom: 'Paragraphe', d: '§' },
  { id: 'pi_variante', nom: 'Pi variante', d: 'ϖ' },
  { id: 'je_min', nom: 'Jé minuscule', d: 'ж' },
  { id: 'h_barre', nom: 'H barré', d: 'Ħ' },
  { id: 'o_barre_min', nom: 'O barré minuscule', d: 'ø' },
  { id: 'cherokee_a', nom: 'Cherokee A', d: 'Ꮜ' },
  { id: 'o_barre_maj', nom: 'O barré majuscule', d: 'Ø' },
  { id: 'gamma_latin', nom: 'Gamma latin', d: 'ɣ' },
  { id: 'phi_min', nom: 'Phi minuscule', d: 'φ' },
  { id: 'theta_min', nom: 'Thêta minuscule', d: 'θ' },
  { id: 'omega_maj', nom: 'Oméga majuscule', d: 'Ω' },
  { id: 'soleil', nom: 'Soleil', d: '☼' },
  { id: 'trefle_noir', nom: 'Trèfle noir', d: '♣' },
  { id: 'superieur', nom: 'Supérieur à', d: '>' },
  { id: 'inferieur', nom: 'Inférieur à', d: '<' },
  { id: 'croche', nom: 'Note de musique (Croche)', d: '♪' },
  { id: 'double_croche', nom: 'Double croche', d: '♫' },
  { id: 'guillemet', nom: 'Guillemets', d: '«' },
  { id: 'omega_min', nom: 'Oméga minuscule', d: 'ω' },
  { id: 'egal', nom: 'Égal', d: '=' },
  { id: 'livre_sterling', nom: 'Livre sterling', d: '£' },
  { id: 'different', nom: 'Différent de', d: '≠' },
  { id: 'shin_hebreu', nom: 'Shin hébreu', d: 'ש' },
  { id: 'cercle_barre', nom: 'Cercle barré', d: '⊖' },
  { id: 'croix_malte', nom: 'Croix', d: '†' },
  { id: 'infini', nom: 'Infini', d: '∞' }
];